[languages]
python = ['ruff format --config indent-width=2 --config line-length=79 -']
rust = ['rustfmt']
rs = ['rustfmt']
lua = ["stylua -s -"]
c = ['clang-format -style=Google']
go = ["gofmt"]
golang = ["gofmt"]
ocaml = ["ocamlformat --name stdin.ml -"]
ml = ["ocamlformat --name stdin.ml -"]
haskell = ["ormolu --no-cabal --stdin-input-file stdin.hs"]
hs = ["ormolu --no-cabal --stdin-input-file stdin.hs"]
mojo = ["mojo format -"]
