break_into_partial_movies: false
camera_resolutions:
  default_resolution: 4k
  4k: 3840x2160
  high: 1920x1080
  low: 854x480
  medium: 1280x720
directories:
  mirror_module_path: false
  output: content/thoughts/images
  raster_images: content/thoughts/images
  sounds: content/thoughts/images
  vector_images: content/thoughts/images
fps: 30
full_screen: false
style:
  background_color: "#333333"
  font: Newsreader
  tex_template: default
universal_import_line: from manimlib import *
window_monitor: 0
window_position: UR
