packages:
  - ./

allowBuilds:
  '@parcel/watcher': true
  bufferutil: true
  core-js-pure: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  utf-8-validate: true
  workerd: true

minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.119'
  - ai@6.0.190

onlyBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - core-js-pure
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - utf-8-validate
  - workerd

strictPeerDependencies: true

supportedArchitectures:
  cpu: [x64, arm64]
  os: [win32, darwin, current]
