packages:
  - ./

onlyBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - core-js-pure
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
  - utf-8-validate
  - workerd

strictPeerDependencies: true

supportedArchitectures:
  cpu: [x64, arm64]
  os: [win32, darwin, current]
