[project]
name = "minisdpa"
version = "0.1.0"
description = "sdpa attention, and Triton, FlashAttention, CuTE DSL, CUTLASS"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["numpy>=2.3.3", "torch>=2.8.0"]
