#!/usr/bin/env bash

GIT_ROOT=$(git rev-parse --show-toplevel)
cd "$GIT_ROOT" || exit 1

\rm assets/indices/* static/linkmap && \rm -rf resources
hugo-obsidian -input=content -output=assets/indices -index -root=. && hugo server --enableGitInfo --minify -D
