[package]
name = "fastbpe"
version = "0.1.0"
edition = "2021"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26", features = ["extension-module"] }
fancy-regex = "0.13"
rayon = "1.10"
hashbrown = "0.16"
anyhow = "1"
memmap2 = "0.9"
rustc-hash = "1.1"
