from __future__ import annotations

class Tokenizer:
    @staticmethod
    def from_pretrained(dir: str) -> "Tokenizer": ...
    def encode(self, text: str) -> list[int]: ...
    def decode(self, ids: list[int]) -> str: ...
    def merges_list(self) -> list[tuple[int, int, int]]: ...
    def vocab_pairs(self) -> list[tuple[list[int], int]]: ...
